projects:
  awsamplifygraphql:
    schemaPath: src/graphql/schema.json
    includes:
      - query
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
